### ISSUE TITLE
AttributeError: ur5_mp instance has no attribute 'arm'

### ISSUE THREAD

**Issue by ar-i-enterprise** [lihuang3/ur5_notebook#27]
Hallo LiHuang, I am facing a problem when running the roslaunch method. All the simulation and gazebo launched well. But I am facing a problem at the ur5_mp.py file: I am really new to ROS. Please help. I really need help because I am really desperate.

`Traceback (most recent call last):
  File "/home/mohan/dd_ws/src/ur5_ROS-Gazebo/ur5_mp.py", line 374, in <module>
    mp=ur5_mp()
  File "/home/mohan/dd_ws/src/ur5_ROS-Gazebo/ur5_mp.py", line 63, in __init__
    self.arm = moveit_commander.MoveGroupCommander('manipulator')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 52, in __init__
    self._g = _moveit_move_group_interface.MoveGroupInterface(name, robot_description, ns)
RuntimeError: Unable to connect to move_group action server 'move_group' within allotted time (5s)
[INFO] [1596241103.351390, 0.000000]: Stopping the robot
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 466, in signal_shutdown
    h()
  File "/home/mohan/dd_ws/src/ur5_ROS-Gazebo/ur5_mp.py", line 153, in cleanup
    self.arm.stop()
AttributeError: ur5_mp instance has no attribute 'arm'`

`[ INFO] [1596241103.819728500, 6.237000000]: Using planning interface 'OMPL'
[ INFO] [1596241103.919725800, 6.320000000]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1596241104.057005900, 6.331000000]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1596241104.172064400, 6.397000000]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1596241104.281793600, 6.419000000]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1596241104.386338100, 6.480000000]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1596241104.464261100, 6.490000000]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1596241104.508344700, 6.490000000]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1596241104.563671800, 6.535000000]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1596241104.659348900, 6.535000000]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1596241104.762128000, 6.548000000]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1596241104.864209500, 6.575000000]: Using planning request adapter 'Fix Start State Path Constraints'
[ur5_mp-15] process has died [pid 22712, exit code 1, cmd /home/mohan/dd_ws/src/ur5_ROS-Gazebo/ur5_mp.py /follow_joint_trajectory:=/arm_controller/follow_joint_trajectory __name:=ur5_mp __log:=/root/.ros/log/6ea9e25e-d38c-11ea-92c3-00155d73c6ba/ur5_mp-15.log].
log file: /root/.ros/log/6ea9e25e-d38c-11ea-92c3-00155d73c6ba/ur5_mp-15*.log
[ WARN] [1596241122.326145000, 12.571000000]: Waiting for /follow_joint_trajectory to come up
[ WARN] [1596241139.949147500, 18.616000000]: Waiting for /follow_joint_trajectory to come up
[ INFO] [1596241153.339214100, 22.642000000]: y position of new box: 0.0950119
,

[ INFO] [1596241218.368347700, 43.517000000]: red_blocks_1 has been spawned
[ INFO] [1596241218.536115200, 43.585000000]: ApplyBodyWrench: reference_frame is empty/world/map, using inertial frame, transferring from body relative to inertial frame
[ INFO] [1596241218.582610100, 43.591000000]: red_blocks_1 speed initialized
[ INFO] [1596241218.654149700, 43.603000000]:
[ERROR] [1596241237.322624600, 49.329000000]: Action client not connected: /follow_joint_trajectory
[ INFO] [1596241237.844478400, 49.491000000]: Returned 0 controllers in list
[ INFO] [1596241239.845947700, 50.153000000]: Trajectory execution is managing controllers`

**Comment by learningxiaobai** [comment]
> Hallo LiHuang, I am facing a problem when running the roslaunch method. All the simulation and gazebo launched well. But I am facing a problem at the ur5_mp.py file: I am really new to ROS. Please help. I really need help because I am really desperate.
> 
> `Traceback (most recent call last): File "/home/mohan/dd_ws/src/ur5_ROS-Gazebo/ur5_mp.py", line 374, in <module> mp=ur5_mp() File "/home/mohan/dd_ws/src/ur5_ROS-Gazebo/ur5_mp.py", line 63, in __init__ self.arm = moveit_commander.MoveGroupCommander('manipulator') File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 52, in __init__ self._g = _moveit_move_group_interface.MoveGroupInterface(name, robot_description, ns) RuntimeError: Unable to connect to move_group action server 'move_group' within allotted time (5s) [INFO] [1596241103.351390, 0.000000]: Stopping the robot Traceback (most recent call last): File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 466, in signal_shutdown h() File "/home/mohan/dd_ws/src/ur5_ROS-Gazebo/ur5_mp.py", line 153, in cleanup self.arm.stop() AttributeError: ur5_mp instance has no attribute 'arm'`
> 
> `[ INFO] [1596241103.819728500, 6.237000000]: Using planning interface 'OMPL'
> [ INFO] [1596241103.919725800, 6.320000000]: Param 'default_workspace_bounds' was not set. Using default value: 10
> [ INFO] [1596241104.057005900, 6.331000000]: Param 'start_state_max_bounds_error' was set to 0.1
> [ INFO] [1596241104.172064400, 6.397000000]: Param 'start_state_max_dt' was not set. Using default value: 0.5
> [ INFO] [1596241104.281793600, 6.419000000]: Param 'start_state_max_dt' was not set. Using default value: 0.5
> [ INFO] [1596241104.386338100, 6.480000000]: Param 'jiggle_fraction' was set to 0.05
> [ INFO] [1596241104.464261100, 6.490000000]: Param 'max_sampling_attempts' was not set. Using default value: 100
> [ INFO] [1596241104.508344700, 6.490000000]: Using planning request adapter 'Add Time Parameterization'
> [ INFO] [1596241104.563671800, 6.535000000]: Using planning request adapter 'Fix Workspace Bounds'
> [ INFO] [1596241104.659348900, 6.535000000]: Using planning request adapter 'Fix Start State Bounds'
> [ INFO] [1596241104.762128000, 6.548000000]: Using planning request adapter 'Fix Start State In Collision'
> [ INFO] [1596241104.864209500, 6.575000000]: Using planning request adapter 'Fix Start State Path Constraints'
> [ur5_mp-15] process has died [pid 22712, exit code 1, cmd /home/mohan/dd_ws/src/ur5_ROS-Gazebo/ur5_mp.py /follow_joint_trajectory:=/arm_controller/follow_joint_trajectory __name:=ur5_mp __log:=/root/.ros/log/6ea9e25e-d38c-11ea-92c3-00155d73c6ba/ur5_mp-15.log].
> log file: /root/.ros/log/6ea9e25e-d38c-11ea-92c3-00155d73c6ba/ur5_mp-15*.log
> [ WARN] [1596241122.326145000, 12.571000000]: Waiting for /follow_joint_trajectory to come up
> [ WARN] [1596241139.949147500, 18.616000000]: Waiting for /follow_joint_trajectory to come up
> [ INFO] [1596241153.339214100, 22.642000000]: y position of new box: 0.0950119
> ,
> 
> [ INFO] [1596241218.368347700, 43.517000000]: red_blocks_1 has been spawned
> [ INFO] [1596241218.536115200, 43.585000000]: ApplyBodyWrench: reference_frame is empty/world/map, using inertial frame, transferring from body relative to inertial frame
> [ INFO] [1596241218.582610100, 43.591000000]: red_blocks_1 speed initialized
> [ INFO] [1596241218.654149700, 43.603000000]:
> [ERROR] [1596241237.322624600, 49.329000000]: Action client not connected: /follow_joint_trajectory
> [ INFO] [1596241237.844478400, 49.491000000]: Returned 0 controllers in list
> [ INFO] [1596241239.845947700, 50.153000000]: Trajectory execution is managing controllers`

have you solved？
